packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  '@astrojs/check': ^0.9.10
  happy-dom: ^20.12.0
  '@types/node': ^24.13.3
  astro: ^7.2.10
  typescript: ^6.0.3
  vite-plus: ^0.3.0
  vitest: 4.1.11
  '@vitest/coverage-v8': ^4.1.11

minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.11.0'
  - '@astrojs/markdown-satteri@0.4.0'
  - astro@7.2.10

allowBuilds:
  esbuild: true

overrides:
  vitest: 4.1.11
